### ISSUE TITLE
A question about the transform on the label 

### ISSUE THREAD

**Issue by Balabala-Hong** [wkentaro/pytorch-fcn#114]
Cool work! But I have a question about the transform on the label in your defination of `VOCClassSegBase(data.Dataset)` in the `voc.py`. Why did you replace the pixel value 255 to -1 on the label like this ：  
 `lbl = PIL.Image.open(lbl_file)`
 `lbl = np.array(lbl, dtype=np.int32)`
 `lbl[lbl == 255] = -1`?

**Comment by bhashithe** [comment]
This is specific to the data set more than this package, could be because in labels they are using 255 value to indicate an unlabeled regions.

Library requires(?) the unlabeled data to have a -1 value, in visualization which is coming from the [fcn](https://github.com/wkentaro/fcn) utilities module this will be filled up with random noise. @wkentaro might be able to correct me on this though.

**Comment by wkentaro** [comment]
@bhashithe Thank you for answering this question. Yes, you're right.

I'm filtering negative label of ground truth from the loss: https://github.com/wkentaro/pytorch-fcn/blob/97189cbccb2c9b8bd776b356a1fd4b6c03f67d79/torchfcn/trainer.py#L35
`fcn.utils.visualize_segmentation()` fills random pixel values for negative label: https://github.com/wkentaro/fcn/blob/a29e167b67b11418a06566ad1ddbbc6949575e05/fcn/utils.py#L360-L362

**Comment by Balabala-Hong** [comment]
Thank you for your answers！ :clap::clap::clap:

**Comment by wkentaro** [comment]
👍
