### ISSUE TITLE
FCN feature map crop

### ISSUE THREAD

**Issue by HasnainRaz** [wkentaro/pytorch-fcn#97]
Hey,

I noticed the input is padded by 100 and the output is cropped by 19 pixels. I read the explanation for padding, but I don't understand it. How does it help alignment? Why does the output need to be cropped by 19? 

I want to extract fc7 features from this network, do I need to crop the feature map as well? How do I calculate the crop size for the fc7 layer, would you have any idea?

**Comment by wdmwhh** [comment]
I'm glad that I can answer the question.
Take fcn-8s for example.
Suppose the size of the image is x. Denote (conv1, relu1, pool1; ...; conv3, relu3, pool3) as Stage1. Denote (conv4, relu4, pool4) as Stage2. Denote (conv5, relu5, pool5; fc6, fc7) as Stage3.
After Stage1, the size of the feature map s1 is (x+198)/8.0.
After Stage2, the size of the feature map s2 is (x+198)/16.0.
After Stage3, the size of the feature map s3 is (x+198)/32.0. 
Upsample s3 and get another feature map s3_, whose size is (x+38)/16.0.
Due to (x+198)/16.0 - (x+38)/16.0 = 10 and 10 / 2 = 5, so s2 is cropped by 5.
Upsample (s3_, s2) and get another feature map s2_, whose size is (x+54)/8.0.
Due to (x+198)/8.0 - (x+54)/8.0 = 18 and 18 / 2 = 9, so s1 is cropped by 9.
Upsample (s2_, s1) and get another feature map s1_, whose size is (x+62).
Due to (x+62) - x = 62 and 62 / 2 = 31, so s1_ is cropped by 31.
Hope that will help you! Amen!

**Comment by Gunnvant** [comment]
Where are the numbers 198 and 38 coming from?
